armor = [
    {
        "item_name": "Leather Helmet",
        "item_type": "armor",
        "player_slot": "Head",
        "equipped": 0,
        "item_desc": f"A leather helmet to protect you from small scratches.",
        "sell_price": 10,
        "item_amount": 1,
        "upgrades": [0, 1],
        "player_affected_stats": {
            "def_base": 1,
        },
    },
    {
        "item_name": "Leather Chestplate",
        "item_type": "armor",
        "player_slot": "Chest",
        "equipped": 0,
        "item_desc": f"A leather Chestplate to protect you from small scratches.",
        "sell_price": 20,
        "item_amount": 1,
        "upgrades": [0, 1],
        "player_affected_stats": {
            "def_base": 2,
        },
    },
    {
        "item_name": "Leather Leggings",
        "item_type": "armor",
        "player_slot": "Legs",
        "equipped": 0,
        "item_desc": f"Leather leggings to protect you from small scratches.",
        "sell_price": 15,
        "item_amount": 1,
        "upgrades": [0, 1],
        "player_affected_stats": {
            "def_base": 2,
        },
    },
    {
        "item_name": "Leather Boots",
        "item_type": "armor",
        "player_slot": "Feet",
        "equipped": 0,
        "item_desc": f"Leather boots to protect you from small scratches. Try not to stop in puddles.",
        "sell_price": 10,
        "item_amount": 1,
        "upgrades": [0, 1],
        "player_affected_stats": {
            "def_base": 1,
        },
    },
    {
        "item_name": "Tough Leather Helmet",
        "item_type": "armor",
        "player_slot": "Head",
        "equipped": 0,
        "item_desc": f"A tough leather helmet to protect you from slightly stronger scratches.",
        "sell_price": 25,
        "item_amount": 1,
        "upgrades": [0, 3],
        "player_affected_stats": {
            "def_base": 3,
        },
    },
    {
        "item_name": "Tough Leather Chestplate",
        "item_type": "armor",
        "player_slot": "Chest",
        "equipped": 0,
        "item_desc": f"A tough leather chestplate to protect you from slightly stronger scratches.",
        "sell_price": 50,
        "item_amount": 1,
        "upgrades": [0, 3],
        "player_affected_stats": {
            "def_base": 3,
        },
    },
    {
        "item_name": "Tough Leather Leggings",
        "item_type": "armor",
        "player_slot": "Legs",
        "equipped": 0,
        "item_desc": f"Tough leather leggings to protect you from slightly stronger scratches.",
        "sell_price": 40,
        "item_amount": 1,
        "upgrades": [0, 3],
        "player_affected_stats": {
            "def_base": 3,
        },
    },
    {
        "item_name": "Tough Leather Boots",
        "item_type": "armor",
        "player_slot": "Feet",
        "equipped": 0,
        "item_desc": f"Tough leather boots to protect you from slightly stronger scratches. "
                     f"Still maybe not the best for puddles...",
        "sell_price": 25,
        "item_amount": 1,
        "upgrades": [0, 3],
        "player_affected_stats": {
            "def_base": 3,
        },
    },
    {
        "item_name": "Iron Helmet",
        "item_type": "armor",
        "player_slot": "Head",
        "equipped": 0,
        "item_desc": f"An iron helmet to protect you from small injuries.",
        "sell_price": 15,
        "item_amount": 1,
        "upgrades": [0, 3],
        "player_affected_stats": {
            "def_base": 3,
        },
    },
    {
        "item_name": "Iron Chestplate",
        "item_type": "armor",
        "player_slot": "Chest",
        "equipped": 0,
        "item_desc": f"An iron chestplate to protect you from small injuries.",
        "sell_price": 15,
        "item_amount": 1,
        "upgrades": [0, 3],
        "player_affected_stats": {
            "def_base": 5,
        },
    },
    {
        "item_name": "Iron Leggings",
        "item_type": "armor",
        "player_slot": "Legs",
        "equipped": 0,
        "item_desc": f"Iron leggings to protect you from small injuries.",
        "sell_price": 15,
        "item_amount": 1,
        "upgrades": [0, 3],
        "player_affected_stats": {
            "def_base": 3,
        },
    },
    {
        "item_name": "Iron Boots",
        "item_type": "armor",
        "player_slot": "Feet",
        "equipped": 0,
        "item_desc": f"Iron boots to protect you from small injuries.",
        "sell_price": 15,
        "item_amount": 1,
        "upgrades": [0, 3],
        "player_affected_stats": {
            "def_base": 3,
        },
    },
]
