equipment = [
    {
        "item_name": "Leather Helmet",
        "item_type": "equipment",
        "player_slot": "Head",
        "equipped": 0,
        "item_desc": f"A leather helmet to protect you from scratches.",
        "item_amount": 1,
        "upgrades": [0, 1],
        "player_affected_stats": {
            "def_base": 1,
        },
    },
    {
        "item_name": "Iron Helmet",
        "item_type": "equipment",
        "player_slot": "Head",
        "equipped": 0,
        "item_desc": f"An iron helmet to protect you from small injuries.",
        "item_amount": 1,
        "upgrades": [0, 3],
        "player_affected_stats": {
            "def_base": 2,
        },
    },
    {
        "item_name": "Wooden Club",
        "item_type": "equipment",
        "player_slot": "Sword",
        "equipped": 0,
        "item_desc": f"A basic wooden club to bash in some heads.",
        "item_amount": 1,
        "upgrades": [0, 1],
        "player_affected_stats": {
            "str_base": 5,
        },
    },
    {
        "item_name": "Primitive Sword",
        "item_type": "equipment",
        "player_slot": "Sword",
        "equipped": 0,
        "item_desc": f"A very primitive sword. Hopefully you know how to handle it...",
        "item_amount": 1,
        "upgrades": [0, 1],
        "player_affected_stats": {
            "str_base": 10,
        },
    },
    {
        "item_name": "Tough Stick",
        "item_type": "equipment",
        "player_slot": "Sword",
        "equipped": 0,
        "item_desc": f"A very tough stick. Pretty sturdy and heavy.",
        "item_amount": 1,
        "upgrades": [0, 0],
        "player_affected_stats": {
            "str_base": 5,
        },
    },
    {
        "item_name": "Sharp Stone",
        "item_type": "equipment",
        "player_slot": "Sword",
        "equipped": 0,
        "item_desc": f"A pretty sharp stone. It's difficult to not cut oneself while handling it.",
        "item_amount": 1,
        "upgrades": [0, 0],
        "player_affected_stats": {
            "str_base": 3,
        },
    },
    {
        "item_name": "Sturdy Wooden Axe",
        "item_type": "equipment",
        "player_slot": "Sword",
        "equipped": 0,
        "item_desc": f"A pretty sharp stone. It's difficult to not cut oneself while handling it.",
        "item_amount": 1,
        "upgrades": [0, 3],
        "player_affected_stats": {
            "str_base": 15,
        },
    },
    {
        "item_name": "Wooden Shield",
        "item_type": "equipment",
        "player_slot": "Shield",
        "equipped": 0,
        "item_desc": f"A basic wooden shield to block some damage.",
        "item_amount": 1,
        "upgrades": [0, 2],
        "player_affected_stats": {
            "def_base": 3,
        },
    },
]
