equipment = [
    {
        "item_name": "Wooden Club",
        "item_type": "equipment",
        "player_slot": "Sword",
        "equipped": 0,
        "item_desc": f"A basic wooden club to bash in some heads.",
        "sell_price": 5,
        "item_amount": 1,
        "upgrades": [0, 1],
        "player_affected_stats": {
            "str_base": 5,
        },
    },
    {
        "item_name": "Primitive Sword",
        "item_type": "equipment",
        "player_slot": "Sword",
        "equipped": 0,
        "item_desc": f"A very primitive sword. Hopefully you know how to handle it...",
        "sell_price": 5,
        "item_amount": 1,
        "upgrades": [0, 1],
        "player_affected_stats": {
            "str_base": 10,
        },
    },
    {
        "item_name": "Tough Stick",
        "item_type": "equipment",
        "player_slot": "Sword",
        "equipped": 0,
        "item_desc": f"A very tough stick. Pretty sturdy and heavy.",
        "sell_price": 5,
        "item_amount": 1,
        "upgrades": [0, 0],
        "player_affected_stats": {
            "str_base": 5,
        },
    },
    {
        "item_name": "Sharp Stone",
        "item_type": "equipment",
        "player_slot": "Sword",
        "equipped": 0,
        "item_desc": f"A pretty sharp stone. It's difficult not to cut oneself while handling it.",
        "sell_price": 3,
        "item_amount": 1,
        "upgrades": [0, 0],
        "player_affected_stats": {
            "str_base": 3,
        },
    },
    {
        "item_name": "Sturdy Wooden Axe",
        "item_type": "equipment",
        "player_slot": "Sword",
        "equipped": 0,
        "item_desc": f"A good Axe. Almost made with good craftsmanship.",
        "sell_price": 10,
        "item_amount": 1,
        "upgrades": [0, 3],
        "player_affected_stats": {
            "str_base": 15,
        },
    },
    {
        "item_name": "Wooden Shield",
        "item_type": "equipment",
        "player_slot": "Shield",
        "equipped": 0,
        "item_desc": f"A basic wooden shield to block some damage.",
        "sell_price": 4,
        "item_amount": 1,
        "upgrades": [0, 2],
        "player_affected_stats": {
            "def_base": 3,
        },
    },
]
