materials = [
    {
        "item_name": "Green Herb",
        "item_type": "material",
        "item_desc": f"A green herb that can be used for crafting.",
        "sell_price": 5,
        "item_amount": 1,
    },
    {
        "item_name": "Red Herb",
        "item_type": "material",
        "item_desc": f"A red herb that can be used for crafting.",
        "sell_price": 5,
        "item_amount": 1,
    },
    {
        "item_name": "Boar Hide",
        "item_type": "material",
        "item_desc": f"Hide from a small boar.",
        "sell_price": 3,
        "item_amount": 1,
    },
    {
        "item_name": "Tough Boar Hide",
        "item_type": "material",
        "item_desc": f"Thick hide from a large boar.",
        "sell_price": 7,
        "item_amount": 1,
    },
    {
        "item_name": "Boar Tusk",
        "item_type": "material",
        "item_desc": f"A Tusk from a boar. Can be used for crafting.",
        "sell_price": 3,
        "item_amount": 1,
    },
    {
        "item_name": "Large Boar Tusk",
        "item_type": "material",
        "item_desc": f"A large Tusk from a boar. Can be used for crafting.",
        "sell_price": 7,
        "item_amount": 1,
    },
    {
        "item_name": "Stick",
        "item_type": "material",
        "item_desc": f"A stick from a Tree. "
                     f"Try not to obtain too many or you'll may find yourself in a sticky situation. ",
        "sell_price": 1,
        "item_amount": 1,
    },
    {
        "item_name": "Small Rock",
        "item_type": "material",
        "item_desc": f"It's a small rock... It now no longer lies in your way.",
        "sell_price": 1,
        "item_amount": 1,
    },
    {
        "item_name": "Mushroom",
        "item_type": "material",
        "item_desc": f"An edible, delicious Mushroom.",
        "sell_price": 4,
        "item_amount": 1,
    },
    {
        "item_name": "Poisonous Mushroom",
        "item_type": "material",
        "item_desc": f"A Mushroom from the forest. Tastes a bit funny...",
        "sell_price": 3,
        "item_amount": 1,
    },
]
